name: Node.js Package

on: ['push']

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
#       - run: echo ${{secrets.NPM_TOKEN}} | awk '{print length($0)}'
#       - name: create .npmrc
#         run: echo "//registry.npmjs.org/:_authToken=${{env.NPM_TOKEN}}" > .npmrc
#         working-directory: ./src
      - name: publish
        run: npm publish
        working-directory: ./src
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
