name: Node.js Package

on:
  push:
    tags:
      - "release/**"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
        working-directory: ./src
      - name: publish
        run: npm publish
        working-directory: ./src
