name: Node.js Package

on: ['push']

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm i @xsahxl/s@3.x -g
      - run: s3 config add --keyList key1,key2,key3 --valueList value1,value2,value3 -a wss-root -f
      - run: s3 config get
